-- ========== 大禹热区 登录系统 数据库脚本 ==========
-- 在 Supabase 控制台 → SQL Editor → 粘贴本文件 → Run
-- 用你现有的同一个 Supabase 项目即可(只新增表, 与 lehai_users / bjl_users 互不影响)

-- 1) 用户表
create table if not exists dayu_users (
  id          bigint generated by default as identity primary key,
  username    text unique not null,           -- 账号
  password    text not null,                  -- 密码
  status      text not null default 'active', -- active=启用 / disabled=停用
  expire_at   timestamptz,                    -- 到期时间; 留空=永久
  device_id   text,                           -- 绑定设备; 留空=未绑定
  note        text,                           -- 备注(客户名)
  created_at  timestamptz default now()
);

-- 2) 设置表(管理员密码)
create table if not exists dayu_settings (
  key   text primary key,
  value text
);
insert into dayu_settings (key, value) values ('admin_pw', '888888')
  on conflict (key) do nothing;

-- 3) 开启 RLS, 放行 public (★关键:新版publishable key必须用 to public, 不能用 to anon)
alter table dayu_users    enable row level security;
alter table dayu_settings enable row level security;

drop policy if exists dayu_users_all    on dayu_users;
drop policy if exists dayu_settings_all on dayu_settings;

create policy dayu_users_all    on dayu_users    for all to public using (true) with check (true);
create policy dayu_settings_all on dayu_settings for all to public using (true) with check (true);

-- 完成! 默认管理员密码 888888
-- 建议: 上线后在管理后台改掉管理员密码
